include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    require_trailing_commas: true
