targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            database: lib/database.dart
            legacy_app_state: lib/legacy_app_state_database.dart
            legacy_profile: lib/legacy_profile_database.dart
