name: market_monk
description: Track stocks quickly and easily
version: 1.0.26+27
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  yahoo_finance_data_reader: ^1.0.11
  fl_chart: ^0.70.1
  intl: ^0.20.1
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  drift_dev: ^2.23.1
  test: ^1.25.8
  sqlite3_flutter_libs: ^0.5.28
  flutter_launcher_icons: ^0.14.2
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1
  http: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix:
    git:
      url: https://github.com/insertjokehere/msix.git
      ref: msvc_redist
  build_runner: ^2.4.14
flutter:
  uses-material-design: true
  assets:
    - assets/
msix_config:
  msstore_appId: 9PP4HKV1CMWC
  display_name: MarketMonk
  publisher_display_name: CodeSail Academy
  identity_name: FrisbeeSoftware.MarketMonk
  msix_version: 1.0.7.0
  logo_path: assets/meditation.png
  trim_logo: false
  publisher: CN=BB0811CB-EED5-441C-BE1B-D31F391F76DE
  store: true
  capabilities: internetClient
