name: Android Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK & appbundle
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" | base64 -d > android/key.properties
          echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > ./android/massive.jks
          flutter build appbundle
          flutter build apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.codesail.market_monk
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          status: completed
